### ISSUE TITLE
Replace MySQL with PostgreSQL

### ISSUE THREAD

**Issue by andrepoleza** [mtmacdonald/docker-laravel#10]
I'm trying to build a Laravel application (using [Wercker](wercker.com)) and when I try to run the unit tests I got this message:

```
Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver
```

Perhaps this occurs because the image is assuming that I'll always use MySQL and thus didn't install packages like `php5-pgsql`, but that's not the case. My question is: how could I replace MySQL with PostgreSQL?

Cheers.

**Comment by arcanedev-maroc** [comment]
Why not install both ?

**Comment by hopewise** [comment]
I got the same issue, although I am linking to a postgres container, but I got the error could not find driver, it seems I have to install postgres within the same laravel container.. right?
