### ISSUE TITLE
SSH, Connection timed out

### ISSUE THREAD

**Issue by hopewise** [mtmacdonald/docker-laravel#12]
At windows 10, I had downloaded the insecure_key :

```
$ chown `whoami` insecure_key
chown: invalid user: ‘Samir’
```

And if I try to connect:

```
$ docker inspect testing_phpstorm | grep IPA
        "SecondaryIPAddresses": null,
        "IPAddress": "172.17.0.4",
                "IPAMConfig": null,
                "IPAddress": "172.17.0.4",

$  ssh -i ./insecure_key root@172.17.0.4
ssh: connect to host 172.17.0.4 port 22: Connection timed out
```

then I mapped port 20 to 220, and tried again:

```
$ ssh -i ./insecure_key root@172.17.0.4 -p 220
ssh: connect to host 172.17.0.4 port 220: Connection timed out
```

Can you please help?

**Comment by hopewise** [comment]
I found it! port 22 is not exposed,
I have added:

    EXPOSE 22

to the Dockerfile, and its working, thanks

**Comment by pixsiro** [comment]
Hi, 
in which container did you add  `EXPOSE 22`?

**Comment by hopewise** [comment]
the container that I was trying to ssh into .. sorry but its about two years now, I've almost forgotten 😃
