### ISSUE TITLE
Improvement: Make MySQL optional

### ISSUE THREAD

**Issue by onbjerg** [mtmacdonald/docker-laravel#6]
On our setup, we use Postgres instead of MySQL. Additionally, our database runs in its own container.

It would be nice to add some configuration for disabling MySQL, as it would pretty much just waste server resources on my setup.

**Comment by mtmacdonald** [comment]
If you comment out or remove `/etc/supervisord/mysql.conf` then MySQL will not start or be supervised by Supervisord. Will keep multiple databases in mind for a future release.
