### ISSUE TITLE
insecure_key failure

### ISSUE THREAD

**Issue by be-codified** [mtmacdonald/docker-laravel#7]
Hi,

I am getting an error:

"Warning: Failed to create the file insecure_key: Operation not supported
curl: (23) Failed writing body (0 != 1675)"

What could be wrong?

**Comment by mtmacdonald** [comment]
Which operating system are you using? I've tested this on Ubuntu 14.04 LTS with curl 7.35.0 and can't reproduce your issue.

**Comment by mtmacdonald** [comment]
Closing this as it is no longer relevant. SSH is removed in docker-laravel 1.4.0 (use docker exec instead to access a container).
